#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'tutorial_types'

INT32CONSTANT = 9853

MAPCONSTANT = {
  %q"hello" => %q"world",
  %q"goodnight" => %q"moon",
}

